repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.13.4
    hooks:
      - id: pylint
        additional_dependencies: [django, pylint-django]
        args:
          - --max-line-length=99
          - --rcfile=.pylintrc
          - -d duplicate-code
          - --disable=django-not-configured
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
